lux-group/lib-global

.babelrc
.eslintrc.json
compiled/currency/index.js
compiled/flights/index.js
compiled/index.js
compiled/offer/duration.js
compiled/offer/flexiNights.js
compiled/offer/index.js
compiled/vendor/index.js
package.json
src/currency/index.js
src/flights/index.js
src/offer/duration.js
src/offer/flexiNights.js
test/offer/flexiNights.test.js
yarn.lock

The calculations that were done to generate the options for a package had two errors:
- The `packageId` was set incorrectly to the `offerPackage.id` - it should've been the `id_salesforce_external`
- Tours were returning `NaN` prices, this was due to `extraNights` being undefined and causing the calculation to fail.
Refactored the functions to make them a bit smaller.
All the actual work is done in the flexiNights files.
Other changes:
- Updated babel to latest, also supports latest syntax
- Updated eslint to latest, turns out this made quite a formatting changes...

Fix flexi nights calculation

---

.circleci/config.yml
README.md
index.d.ts
package.json
yarn.lock

Adds the types that @zediah kindly added to Public Offer. We'd now like to use them in the Admin Portal.
* Update CI/CI to publish master for new versions
* Bump mocha to v6 (to remove yarn audit warning)

Add types from public offer

---

package.json

Publish failed.
Somehow 2.3.0 and 2.3.1 are already published: https://www.npmjs.com/package/@luxuryescapes/lib-global
Use 2.3.2

2.3.2 because 2.3.0 is already used

---

compiled/offer/pricing.js
package.json
src/offer/pricing.js
test/offer/pricing.test.js

Adds a fix for the handling of default values which was accidentally changed with the tax calculation fixes

fix(taxes) default to per night instead of per stay

---

compiled/offer/pricing.js
package.json
src/offer/pricing.js
test/offer/pricing.test.js

We need to allow calculate total for each tax as it's required to calculate non-commissionable tax&fee.
I didn't round the result for each taxAndFee as it's mostly for internal use and calculation so rounding them won't be necessary imo, but can leave it as an option if anyone thinks we should allow that.

Allow calculated total for each tax

---

compiled/offer/pricing.js
package.json
src/offer/pricing.js
test/offer/pricing.test.js

This is another fix for incorrect tax calculations. Multiplying of nightly percentage taxes is removed.

fix(taxes): fix tax calculations - don't multiply percentage taxes

---

compiled/date/index.js
compiled/date/timezones.js
compiled/index.js
index.d.ts
package.json
src/date/index.js
src/date/timezones.js
src/index.js
test/date/index.test.js

We use these function in a lot of places and all time make a duplicates.
Native Date use little memory and CPU for calculations
we use similar functions 
svc-reservations
svc-connection-synxis
lib-refunds
TESTS
LUXON start: 30.027ms
MOMENT start: 3.951ms
date-fns: start: 1.34ms
DATE: start: 0.325ms

feat(date): add date tools

---

compiled/offer/pricing.js
index.d.ts
package.json
src/offer/pricing.js
test/offer/pricing.test.js

Ticket https://aussiecommerce.atlassian.net/browse/CONTB-614
It's more refactoring since the calculation of calculateAmountForEachTax function needs different calculation formula in diff places. Also **calculateAmountForEachTax** function used to be used for internally and externally purposes - now it's divided by responsibility and used only externally

feat(inclusions): [CONTB-614] Calculate the correct Tax/Fee as 'Payable at Property'

---

compiled/index.js
compiled/property/index.js
index.d.ts
package.json
src/index.js
src/property/index.js
test/property/index.test.js
tsconfig.json

https://aussiecommerce.atlassian.net/browse/USZ-11
The work being done in both svc-res and svc-bedbank share a common list of property type and category.  To reduce duplication, this list has now been created in lib-global with helpers to manage the mapping

feat(properties): add categories and type, and helper function to match

---

compiled/property/index.js
index.d.ts
package.json
src/property/index.js
test/property/index.test.js

USZ-11-property-type-category
Missed a useful helper to return just the types, keeping everything isolated here

feat(properties): added helper to get all types

---

index.d.ts
package.json
src/constants/taxesAndFees.ts
src/index.js
src/offer/pricing.js
src/product/constants.js
src/product/index.js
test/offer/pricing.test.js
yarn.lock

https://aussiecommerce.atlassian.net/browse/CONLT-442
Filter tax items according to their product and offer types:
Dynamic product items should only calculate for: LPC and LME
LTE product items should only calculate for LTLE -> hotel
All product items calculates for all.

[CONLT-442] Add product type filtering to taxes and fees

---

index.d.ts
package.json
src/occupancy/index.js
test/occupancy/index.test.js

Occupancy matcher compatibility was broken, undoing that so it continues to work as expected. Moved required occupancy to a new matcher

fix(occupancy): move required occupancy to it's own matcher

---

package.json
src/offer/constants.js
test/offer/dates.test.js

https://aussiecommerce.atlassian.net/browse/CONLT-626
Change default check in limit for last minute escapes to 14 days

feat(lme): change default check in for last minute escapes to 14 days

---

index.d.ts
package.json
src/property/index.js
test/property/index.test.js

https://aussiecommerce.atlassian.net/browse/CONLT-998
We've found that the `defaultTypeForCategory` was being misused.  Instead it makes more sense to have a `isUniqueStay` function.  We now have a third property type - `Rental` - so categories can now belong to multiple types.

feat(rentals): added new Rental property type

---

package.json
src/calendar/constants.js

When this type was added some of the properties weren't set up correctly, which caused issues when it was used.

feat(constants): updated rental offer type

---

index.d.ts
package.json
src/offer/flexiNights.js

Minor refactor and export a function so svc-search can use it. Svc-search can't use the generateAllOptions because it doesn't need to generate every single option. It just needs the logical to calculate the price for extra nights.

Refactor and export calculatePackagePrice function for search

---

index.d.ts
package.json
src/white-label/index.js
src/white-label/tenant-from-brand.js
test/white-label/tenant-from-brand.test.js

[Jira ticket](https://aussiecommerce.atlassian.net/browse/OPEX-1847)
[svc-order PR feedback this work stems from](https://github.com/lux-group/svc-order/pull/3369#discussion_r1625384266)
There exists a `tenantFromBrand` function used in both `svc-order` and `svc-auth`. The aim of this function is determine the correct name of a tenant from a given brand name. This PR aims to dedupe this piece of logic by adding it to this library, and then imported where it needs to be used.

[OPEX-1847]: tenantFromBrand dedupe

---

package.json
src/environment/index.js
test/environment/index.test.js

with how we exported the `environment` object before, clients had to do:
```
import { environment } from "lib/global"
console.log(environment.environment.PRODUCTION)
```
to get the "production" string. However, this wasn't caught because index.d.ts indicates that this is the proper import (and how clients use them currently):
```
import { environment } from "lib/global"
console.log(environment.PRODUCTION)
```
This means that anywhere `environment.PRODUCTION` is being used, it's evaluated to undefined on runtime. This PR introduce a breaking change that corrects the export and align it with index.d.ts definition.

fix!: environment export does not match index.d.ts

---

index.d.ts
package.json
src/offer/pricing.js

Type mismatch between the exposed type `childrenAge` and the implementation using `childrenAges`
Update Occupancts type schema to use plural `childrenAges` (to match the impl)
https://github.com/lux-group/lib-global/blob/e9d03d3723f18c41125d5e4d9032f1c0e588b82f/src/occupancy/index.js#L21
(we could also change the impl but either way it will break other repos as some are ignoring the type and using `childrenAges`, so we stick with the majority of our repos using plural and keep the naming convention consistent)
Repos needing review and potential update
https://github.com/search?q=org%3Alux-group+lib-global+occupancy&type=code

fix(occupants): HP-625: update occupants schema

---

index.d.ts
package.json
src/property/extraGuests.js
test/property/extraGuests.test.js

Fixed a bug where surcharges were incorrectly being applied when guest counts contained invalid values. The issue occurred when calculating extra guests with invalid teenager counts, causing the system to treat empty guest configurations
as having extra guests.
- Invalid guest counts are properly handled
- Added normalization of includedGuests to get function inside extraGuests

[HC-379] - fix: prevent extra guest surchages
