- compiled/vendor/index.js
- src/vendor/index.js
https://aussiecommerce.atlassian.net/browse/LENG-1537
Add a new vendor ID to the LE vendors.
> [LENG-1537] Add new LE vendor ID

- README.md
Update README with how to release npm versions
> Update README with how to release npm versions

- compiled/currency/index.js
- compiled/index.js
- package.json
- src/currency/index.js
- src/index.js
https://aussiecommerce.atlassian.net/browse/LEE-200
> [LEE-200] Add prefix of dollars

- .circleci/config.yml
- package.json
> Publish circleCI

- index.d.ts
> adding currency type

- index.d.ts
- package.json
- src/offer/flexiNights.js
Prices is an array and has a currency_code.
Example: https://api.luxuryescapes.com/api/offers/0062800000J1qZaAAJ
> Prices is an array and has a currency_code

- index.d.ts
- package.json
Incomplete types in the lib are causing type errors in customer portal.
> Fill in missing types

- compiled/offer/pricing.js
- package.json
- src/offer/pricing.js
- test/offer/index.test.js
- test/offer/pricing.test.js
Changed the way taxes are calculated to take into account that taxes are not cumulative - each tax should be assumed to be on the base value and then they are added together
> fix(taxes) fix tax calculation

- README.md
- compiled/offer/pricing.js
- index.d.ts
- package.json
Just realised index.d.ts needs to be updated...
> chore(tax): update calculate tax ts index file

- compiled/calendar/constants.js
- compiled/calendar/index.js
- compiled/index.js
- index.d.ts
- package.json
- src/calendar/constants.js
- src/calendar/index.js
- src/index.js
- test/calendar/index.test.js
Moved methods from calendar to lib
> feat(calendar): add methods for calendar

- compiled/offer/pricing.js
- index.d.ts
- src/offer/pricing.js
- test/offer/pricing.test.js
Ticket [https://aussiecommerce.atlassian.net/browse/CONTB-614](https://aussiecommerce.atlassian.net/browse/CONTB-614)
we should be able to have **Property Fees**(Due at property) for offer as well as it is implemented for bedbank offers
> feat(inclusions): [CONTB-614] Calculate the correct Tax/Fee as 'Payable at Property'

- compiled/offer/pricing.js
- package.json
- src/offer/pricing.js
- test/offer/pricing.test.js
we did not use number of rooms for about tax
> fix(rooms): add count of rooms

- compiled/property/index.js
- index.d.ts
- package.json
- src/property/index.js
- test/property/index.test.js
https://aussiecommerce.atlassian.net/browse/USZ-11
This change was done to reduce the chance of typos occurring in other services
> fix(category): amended to export all category names individually

- compiled/property/index.js
- index.d.ts
- package.json
- src/property/index.js
> fix(properties): exported property type codes

- index.d.ts
- package.json
- src/property/index.js
- test/property/index.test.js
https://aussiecommerce.atlassian.net/browse/USZ-55
Just like it says on the tin - added `Hotels & Resorts` category
> [USZ-55] feat(categories): added 'Hotels & Resorts' category

- index.d.ts
- package.json
- src/offer/pricing.js
- test/offer/pricing.test.js
> fix: renamed function in pricing

- index.d.ts
- package.json
> CONLT-280 add isFlash flag and check if excluding at property fees

- package.json
- src/occupancy/index.js
- test/occupancy/index.test.js
https://aussiecommerce.atlassian.net/browse/CONTB-840
> fix: make occupancy is required

- package.json
Related to changes on tax filtering https://aussiecommerce.atlassian.net/browse/CONLT-442
> [CONLT-442] Bump package version

- index.d.ts
- package.json
- src/property/index.js
- test/property/index.test.js
JIRA: [https://aussiecommerce.atlassian.net/browse/CONTB-912](https://aussiecommerce.atlassian.net/browse/CONTB-912)
> feat (connections) [CONTB-912] Add a category to property edit page in admin named

- package.json
- src/environment/index.js
- src/index.js
Add production, spec, test etc consts
> Add consts for environment

- package.json
- src/white-label/dynamic-tags.js
> expose brandContent

- package.json
- src/white-label/dynamic-tags.js
Async without await is useless it is causing problems integrating dyanmic tags with svc-offer
> Exp 1511: Remove useless async

- index.d.ts
- package.json
- src/calendar/constants.js
> fix(issue): calendar

- src/white-label/constants.js
> Add leagenthub to the constant list

- package.json
- src/property/extraGuests.js
- test/property/extraGuests.test.js
Problem with calculations after exchange currency
example 
before
748 * 7 = 5236
after
748.78 * 7 = 5241.46
> fix(calculation): exchange rates

- index.d.ts
- package.json
- Update type definition for strummer.
- Bumb version
> [HC-267-fix] fix: type definition

- index.d.ts
- package.json
- src/occupancy/index.js
- test/occupancy/index.test.js
https://aussiecommerce.atlassian.net/browse/HC-380
- Adding maxTeenagerAge parameter
- Adding teenager counting logic to the countOccupants function
- Added tests and updated tests to handle teenagers
> [HC-380] - feat(occupancy): add support for teenager occupancy
